config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :friends 
  #get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'home/about'
  root 'home#index'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord

    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

          has_many :friends
          acts_as_messageable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [ :index, :show ]
  before_action :correct_user, only: [ :edit, :update, :destroy ]
  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    # @friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    #@friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy!

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not authorized to edit this friend" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :instagram, :user_id )
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # this is where we write code that works 
    # for the home view... duh!
  end

  def about
      @about_me = "My name is Ben Remy"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
  <%= form.text_field :first_name, placeholder: "First Name" %>
</div>
<br/>

  <div>
  <%= form.text_field :last_name, placeholder: "Last Name" %>
</div>
<br/>

<div>
<%= form.text_field :email, placeholder: "Email" %>
</div>
<br/>

<div>
  <%= form.text_field :phone, placeholder: "Phone Number" %>
</div>
<br/>

<div>
  <%= form.text_field :instagram, placeholder: "Instagram" %>
</div>
<br/>

<div>
  <%= form.number_field :user_id, 
      id: :friend,
      value: current_user.id,
      type: :hidden %>
</div>
<br/>


  <div>
    <br/>
    <%= form.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <p>
    <strong>First name:</strong>
    <%= friend.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= friend.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= friend.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= friend.phone %>
  </p>

  <p>
    <strong>Instagram:</strong>
    <%= friend.instagram %>
  </p>

</div>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend, class: "btn btn-secondary"%> |
  <%= link_to "Back to friends", friends_path, class: "btn btn-dark" %>
</div>

app/views/friends/index.html.erb
<p id="notice"><%= notice %></p>


<table class="table table-striped
                    table-bordered
                    table-hover">
  <thead class="thead-dark">
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Instagram</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friends.each do |friend| %>

  <tbody>

    <tr>
      <td><%= friend.first_name %></td>
      <td><%= friend.last_name %></td>
      <td><%= friend.email %></td>
      <td><%= friend.phone %></td>
      <td><%= friend.instagram %></td> 
      <td><%= link_to 'Show', friend, class: "btn btn-primary" %></td>
      <td><%= link_to 'Edit', edit_friend_path(friend), class: "btn btn-success" %></td>
      <td><%= button_to 'Destroy', friend, class: "btn btn-danger", method: :delete%></td>
    </tr>
  </tbody>
<% end %>
</table>

<br>
<%= link_to 'New Friend', new_friend_path, class: 'btn btn-primary' %>

app/views/friends/new.html.erb
<h1>New friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>

  <%= link_to "Back to friends", friends_path, class: "btn btn-secondary" %>
</div>

app/views/friends/show.html.erb
<div class="container mt-5">
  <div class="card">
    <div class="card-header">
      <h2><%= @friend.first_name %> <%= @friend.last_name %></h2>
    </div>
    <div class="card-body">
      <h5 class="card-title">Contact Details</h5>
      <p class="card-text">
        <strong>Email:</strong> <%= @friend.email %><br>
        <strong>Phone:</strong> <%= @friend.phone %><br>
        <strong>Instagram:</strong> <%= @friend.instagram %>
      </p>
      <%= link_to 'Edit', edit_friend_path(@friend), class: 'btn btn-primary' %> |
      <%= link_to 'Back', friends_path, class: 'btn btn-secondary' %>
    </div>
  </div>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Friend App', root_path, class:"navbar-brand" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav_item">
      <%= link_to 'About us', home_about_path, class: 'nav-link' %>
      </li>

      <li class="nav_item">
        <%= link_to 'Show Friends', friends_path, class: 'nav-link' %>
      </li>

  <% if user_signed_in? %>

      <li class="nav_item">
      <%= link_to 'Add Friend', new_friend_path, class: 'nav-link' %>
      </li>

      <li class="nav_item">
      <%= link_to 'Sign Out', destroy_user_session_path, 
      method: :delete,
      class: 'nav-link' %>
      </li>

      <li class="nav_item">
      <%= link_to 'Edit Profile', edit_user_registration_path, class: 'nav-link' %>
       </li>

  <% else %>

      <li class="nav_item">
        <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
      </li>

      <li class="nav_item">
        <%= link_to 'Sign In', new_user_session_path,
        class: 'nav-link' %>
      </li>
      
  <% end %>
     
     
</nav>

app/views/home/about.html.erb
<h1>About us...</h1>

<p> 
    <%= @about_me %>

<p>

app/views/home/index.html.erb
<h1>Hello World!</h1>
This is my first rails webpage

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <title>Friends App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'application', 'data-turbo-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>
  <body>

    <%= render 'home/header' %>
    <div class="container">
    <br/>
    <%= yield %>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    -->
  </body>
</html>